version: '3.8'

services:
  employee-front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: employee-front-container
    restart: unless-stopped